-- 0001: Initial schema for the Philax MVP.
-- Primary keys are UUIDs generated by the application (UUIDv7); the DB default is
-- a random UUID fallback. Public APIs never expose sequential ids.

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Users, sessions, billing
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name  TEXT,
  locale        TEXT NOT NULL DEFAULT 'en' CHECK (locale IN ('en', 'es', 'ar')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_lower_idx ON users (lower(email));

CREATE TABLE sessions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash   TEXT NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at   TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON sessions (user_id);
CREATE INDEX sessions_expires_idx ON sessions (expires_at);

CREATE TABLE subscriptions (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  plan               TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro')),
  status             TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'canceled', 'past_due')),
  current_period_end TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Knowledge: sources, chunks, embeddings
-- ---------------------------------------------------------------------------
CREATE TABLE sources (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          TEXT UNIQUE,
  title         TEXT NOT NULL,
  author        TEXT,
  publisher     TEXT,
  url           TEXT,
  published_at  TEXT,
  source_type   TEXT NOT NULL CHECK (source_type IN ('primary', 'secondary', 'academic', 'article', 'book', 'user-provided')),
  language      TEXT NOT NULL DEFAULT 'en',
  origin        TEXT NOT NULL CHECK (origin IN ('seed', 'curated', 'user')),
  -- User-provided sources are private to their owner and deleted with them.
  owner_user_id UUID REFERENCES users (id) ON DELETE CASCADE,
  content_hash  TEXT,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((origin = 'user') = (owner_user_id IS NOT NULL))
);
CREATE INDEX sources_owner_idx ON sources (owner_user_id);

CREATE TABLE perspectives (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug             TEXT NOT NULL UNIQUE,
  label            TEXT NOT NULL,
  description      TEXT NOT NULL,
  assumptions      TEXT[] NOT NULL DEFAULT '{}',
  "values"         TEXT[] NOT NULL DEFAULT '{}',
  relevant_domains TEXT[] NOT NULL DEFAULT '{}',
  -- Curated slugs of perspectives this one is in principled tension with.
  contrasts        TEXT[] NOT NULL DEFAULT '{}',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE characters (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug              TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  display_name      TEXT NOT NULL,
  type              TEXT NOT NULL CHECK (type IN ('philosopher', 'scientist', 'writer', 'economist', 'thinker', 'school')),
  birth_year        INTEGER,
  death_year        INTEGER,
  era               TEXT NOT NULL,
  representation    TEXT NOT NULL CHECK (representation IN ('historical', 'contemporary')),
  worldview_summary TEXT NOT NULL,
  biography         TEXT NOT NULL,
  domains           TEXT[] NOT NULL DEFAULT '{}',
  is_active         BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE works (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  character_id UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  title        TEXT NOT NULL,
  year         INTEGER,
  source_id    UUID REFERENCES sources (id) ON DELETE SET NULL,
  UNIQUE (character_id, title)
);
CREATE INDEX works_source_idx ON works (source_id);

CREATE TABLE source_chunks (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id      UUID NOT NULL REFERENCES sources (id) ON DELETE CASCADE,
  character_id   UUID REFERENCES characters (id) ON DELETE CASCADE,
  ordinal        INTEGER NOT NULL,
  content        TEXT NOT NULL,
  knowledge_kind TEXT NOT NULL CHECK (knowledge_kind IN ('biographical_fact', 'documented_position', 'concept', 'scholarly_interpretation', 'interpretation', 'user_content')),
  locator        TEXT,
  fts_config     REGCONFIG NOT NULL DEFAULT 'english',
  tsv            TSVECTOR GENERATED ALWAYS AS (to_tsvector(fts_config, content)) STORED,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_id, ordinal)
);
CREATE INDEX source_chunks_tsv_idx ON source_chunks USING GIN (tsv);
CREATE INDEX source_chunks_character_idx ON source_chunks (character_id);

CREATE TABLE embeddings (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chunk_id   UUID NOT NULL REFERENCES source_chunks (id) ON DELETE CASCADE,
  model      TEXT NOT NULL,
  embedding  VECTOR(1536) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (chunk_id, model)
);
CREATE INDEX embeddings_hnsw_idx ON embeddings USING hnsw (embedding vector_cosine_ops);
CREATE INDEX embeddings_model_idx ON embeddings (model);

CREATE TABLE character_concepts (
  character_id UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  concept      TEXT NOT NULL,
  description  TEXT NOT NULL,
  source_id    UUID REFERENCES sources (id) ON DELETE SET NULL,
  locator      TEXT,
  chunk_id     UUID REFERENCES source_chunks (id) ON DELETE SET NULL,
  PRIMARY KEY (character_id, concept)
);

CREATE TABLE character_positions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  character_id   UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  topic          TEXT NOT NULL,
  statement      TEXT NOT NULL,
  knowledge_kind TEXT NOT NULL CHECK (knowledge_kind IN ('documented_position', 'scholarly_interpretation', 'interpretation')),
  source_id      UUID REFERENCES sources (id) ON DELETE SET NULL,
  locator        TEXT,
  chunk_id       UUID REFERENCES source_chunks (id) ON DELETE SET NULL
);
CREATE INDEX character_positions_character_idx ON character_positions (character_id);

CREATE TABLE character_perspectives (
  character_id   UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  perspective_id UUID NOT NULL REFERENCES perspectives (id) ON DELETE CASCADE,
  -- 1 = touches on, 2 = significant, 3 = paradigmatic representative.
  strength       SMALLINT NOT NULL CHECK (strength BETWEEN 1 AND 3),
  PRIMARY KEY (character_id, perspective_id)
);
CREATE INDEX character_perspectives_perspective_idx ON character_perspectives (perspective_id);

CREATE TABLE character_relations (
  character_id       UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  other_character_id UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  relation           TEXT NOT NULL CHECK (relation IN ('opposes', 'critiques', 'influenced_by', 'shares_tradition')),
  note               TEXT NOT NULL,
  PRIMARY KEY (character_id, other_character_id, relation),
  CHECK (character_id <> other_character_id)
);

CREATE TABLE character_constraints (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  character_id UUID NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  kind         TEXT NOT NULL CHECK (kind IN ('never_claim', 'anachronism', 'tone', 'scope')),
  rule         TEXT NOT NULL
);
CREATE INDEX character_constraints_character_idx ON character_constraints (character_id);

-- ---------------------------------------------------------------------------
-- Topics and claims
-- ---------------------------------------------------------------------------
CREATE TABLE topics (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  input_type            TEXT NOT NULL CHECK (input_type IN ('text', 'url')),
  input_preview         TEXT NOT NULL,
  -- Raw user input (private; deleted with the debate).
  input_text            TEXT,
  input_url             TEXT,
  source_id             UUID REFERENCES sources (id) ON DELETE SET NULL,
  title                 TEXT,
  summary               TEXT,
  language              TEXT,
  content_type          TEXT,
  domains               TEXT[] NOT NULL DEFAULT '{}',
  concepts              TEXT[] NOT NULL DEFAULT '{}',
  retrieval_keywords    TEXT[] NOT NULL DEFAULT '{}',
  analysis              JSONB,
  prompt_version        TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX topics_user_idx ON topics (user_id);
CREATE INDEX topics_source_idx ON topics (source_id);

CREATE TABLE claims (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id    UUID NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
  local_id    TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('claim', 'evidence', 'assumption', 'question', 'value_judgment', 'prediction', 'definition')),
  text        TEXT NOT NULL,
  related_ids TEXT[] NOT NULL DEFAULT '{}',
  UNIQUE (topic_id, local_id)
);

-- ---------------------------------------------------------------------------
-- Debates
-- ---------------------------------------------------------------------------
CREATE TABLE debates (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  topic_id      UUID NOT NULL UNIQUE REFERENCES topics (id) ON DELETE CASCADE,
  mode          TEXT NOT NULL CHECK (mode IN ('debate', 'challenge')),
  phase         TEXT NOT NULL,
  language      TEXT NOT NULL DEFAULT 'en',
  current_round INTEGER NOT NULL DEFAULT 0,
  plan          JSONB,
  memory        JSONB NOT NULL DEFAULT '{}'::jsonb,
  challenge     JSONB,
  synthesis     JSONB,
  error_code    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at  TIMESTAMPTZ
);
CREATE INDEX debates_user_created_idx ON debates (user_id, created_at DESC);

CREATE TABLE debate_participants (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id        UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  character_id     UUID NOT NULL REFERENCES characters (id) ON DELETE RESTRICT,
  perspective_id   UUID REFERENCES perspectives (id) ON DELETE SET NULL,
  role             TEXT NOT NULL CHECK (role IN ('debater', 'supporter', 'opponent', 'alternative')),
  seat             INTEGER NOT NULL,
  selection_reason TEXT NOT NULL,
  selection_score  REAL,
  UNIQUE (debate_id, character_id),
  UNIQUE (debate_id, seat)
);
CREATE INDEX debate_participants_character_idx ON debate_participants (character_id);

CREATE TABLE debate_rounds (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id    UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  number       INTEGER NOT NULL CHECK (number >= 1),
  phase        TEXT NOT NULL,
  status       TEXT NOT NULL CHECK (status IN ('pending', 'generating', 'completed')),
  plan         JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at   TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  UNIQUE (debate_id, number)
);

CREATE TABLE debate_messages (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id               UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  round_id                UUID NOT NULL REFERENCES debate_rounds (id) ON DELETE CASCADE,
  round_number            INTEGER NOT NULL,
  phase                   TEXT NOT NULL,
  speaker_type            TEXT NOT NULL CHECK (speaker_type IN ('character', 'user')),
  character_id            UUID REFERENCES characters (id) ON DELETE RESTRICT,
  move                    TEXT NOT NULL,
  content                 TEXT NOT NULL,
  reply_to_message_id     UUID REFERENCES debate_messages (id) ON DELETE SET NULL,
  addressed_character_ids UUID[] NOT NULL DEFAULT '{}',
  -- Idempotency key: one accepted message per planned turn.
  turn_key                TEXT NOT NULL,
  validation              JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (debate_id, turn_key),
  CHECK ((speaker_type = 'character') = (character_id IS NOT NULL))
);
CREATE INDEX debate_messages_debate_idx ON debate_messages (debate_id, created_at);
CREATE INDEX debate_messages_round_idx ON debate_messages (round_id);

CREATE TABLE arguments (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id         UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  message_id        UUID NOT NULL UNIQUE REFERENCES debate_messages (id) ON DELETE CASCADE,
  character_id      UUID REFERENCES characters (id) ON DELETE RESTRICT,
  claim             TEXT NOT NULL,
  premises          JSONB NOT NULL,
  conclusion        TEXT NOT NULL,
  assumptions       JSONB NOT NULL,
  evidence          JSONB NOT NULL,
  objections        JSONB NOT NULL,
  source_references JSONB NOT NULL,
  fingerprint       TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX arguments_debate_idx ON arguments (debate_id);

-- Evidence pool retrieved for a debate (the only chunks turns may cite).
CREATE TABLE evidence (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id        UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  chunk_id         UUID NOT NULL REFERENCES source_chunks (id) ON DELETE CASCADE,
  character_id     UUID REFERENCES characters (id) ON DELETE CASCADE,
  label            TEXT NOT NULL,
  retrieval_score  REAL NOT NULL,
  retrieval_method TEXT NOT NULL CHECK (retrieval_method IN ('lexical', 'vector', 'hybrid', 'direct')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (debate_id, chunk_id),
  UNIQUE (debate_id, label)
);
CREATE INDEX evidence_chunk_idx ON evidence (chunk_id);

CREATE TABLE citations (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id  UUID NOT NULL REFERENCES debate_messages (id) ON DELETE CASCADE,
  evidence_id UUID NOT NULL REFERENCES evidence (id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (message_id, evidence_id)
);
CREATE INDEX citations_evidence_idx ON citations (evidence_id);

CREATE TABLE saved_debates (
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  debate_id  UUID NOT NULL REFERENCES debates (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, debate_id)
);
CREATE INDEX saved_debates_debate_idx ON saved_debates (debate_id);

-- ---------------------------------------------------------------------------
-- Usage & observability (no user content is stored here)
-- ---------------------------------------------------------------------------
CREATE TABLE usage_events (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind       TEXT NOT NULL,
  debate_id  UUID REFERENCES debates (id) ON DELETE SET NULL,
  quantity   INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX usage_events_user_kind_idx ON usage_events (user_id, kind, created_at);
CREATE INDEX usage_events_debate_idx ON usage_events (debate_id);

CREATE TABLE ai_calls (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  debate_id          UUID REFERENCES debates (id) ON DELETE SET NULL,
  topic_id           UUID REFERENCES topics (id) ON DELETE SET NULL,
  operation          TEXT NOT NULL,
  tier               TEXT NOT NULL,
  provider           TEXT NOT NULL,
  model              TEXT NOT NULL,
  prompt_version     TEXT,
  attempt            INTEGER NOT NULL DEFAULT 1,
  latency_ms         INTEGER NOT NULL,
  input_tokens       INTEGER,
  output_tokens      INTEGER,
  estimated_cost_usd NUMERIC(12, 6),
  retrieval_count    INTEGER,
  validation_status  TEXT NOT NULL,
  error_code         TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ai_calls_debate_idx ON ai_calls (debate_id);
CREATE INDEX ai_calls_topic_idx ON ai_calls (topic_id);
CREATE INDEX ai_calls_created_idx ON ai_calls (created_at);
