export * from './framework';
export type { ChatMessage } from './types';
export { topicAnalyzerPrompt } from './templates/topic-analyzer.prompt';
export type { TopicAnalyzerInput } from './templates/topic-analyzer.prompt';
export { characterSelectorPrompt } from './templates/character-selector.prompt';
export type { CharacterSelectorInput } from './templates/character-selector.prompt';
export { debatePlannerPrompt } from './templates/debate-planner.prompt';
export type { DebatePlannerInput } from './templates/debate-planner.prompt';
export { buildTurnPrompt, TURN_OUTPUT_SPEC } from './templates/turn-common';
export type { TurnPromptInput } from './templates/turn-common';
export { openingPrompt } from './templates/opening.prompt';
export { challengePrompt } from './templates/challenge.prompt';
export { responsePrompt } from './templates/response.prompt';
export { crossExaminationPrompt } from './templates/cross-examination.prompt';
export { deepDisagreementPrompt } from './templates/deep-disagreement.prompt';
export { openQuestionPrompt } from './templates/open-question.prompt';
export { userReplyPrompt } from './templates/user-reply.prompt';
export { objectionGeneratorPrompt } from './templates/objection-generator.prompt';
export type { ObjectionGeneratorInput } from './templates/objection-generator.prompt';
export { consistencyCheckerPrompt } from './templates/consistency-checker.prompt';
export type { ConsistencyCheckerInput } from './templates/consistency-checker.prompt';
export { synthesisPrompt } from './templates/synthesis.prompt';
export type { SynthesisInput } from './templates/synthesis.prompt';
export { challengeFramingPrompt } from './templates/challenge-framing.prompt';
export type { ChallengeFramingInput } from './templates/challenge-framing.prompt';
